### ISSUE TITLE
Use of Browser Globals

### ISSUE THREAD

**Issue by wmlutz** [Vashnak/react-toasts#8] opened 2019-03-07 00:31 UTC
Using this for a GatsbyJs site and ran into a problem with the [browser global use](https://www.gatsbyjs.org/docs/debugging-html-builds/). Any thoughts on how to fix it?

**Comment by Vashnak** [comment] 2019-03-14 14:48
Hello, what kind of problem do you have ? Maybe console log or behaviour could help me :)

**Comment by Vashnak** [comment] 2019-04-03 13:12
I guess the problem is related to the issue number 10, I close this now, reopen it if needed

**Closed by Vashnak** 2019-04-03 13:12 UTC
Labels: pending
